-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."2018"
(
    "POP" character varying COLLATE pg_catalog."default",
    "GEONAME" character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."2019"
(
    "POP" character varying COLLATE pg_catalog."default",
    "NAME" character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Population Changes"
(
    "STATEID" character varying COLLATE pg_catalog."default",
    "STATE" character varying COLLATE pg_catalog."default",
    "CHANGE" character varying COLLATE pg_catalog."default",
    "PERCENT" character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Race Changes"
(
    "Race" character varying COLLATE pg_catalog."default",
    "Population 2018" character varying COLLATE pg_catalog."default",
    "Population 2019" character varying COLLATE pg_catalog."default",
    "Racial Percentage 2018" character varying COLLATE pg_catalog."default",
    "Racial Percentage 2019" character varying COLLATE pg_catalog."default",
    "Percentage Change 2018-2019" character varying COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Race Info"
(
    "STATEID" character varying COLLATE pg_catalog."default",
    "STATE" character varying COLLATE pg_catalog."default",
    "WHITEPOP18" character varying COLLATE pg_catalog."default",
    "WHITEPOP19" character varying COLLATE pg_catalog."default",
    "BLACKPOP18" character varying COLLATE pg_catalog."default",
    "BLACKPOP19" character varying COLLATE pg_catalog."default",
    "AIANPOP18" character varying COLLATE pg_catalog."default",
    "AIANPOP19" character varying COLLATE pg_catalog."default",
    "ASPOP18" character varying COLLATE pg_catalog."default",
    "ASPOP19" character varying COLLATE pg_catalog."default",
    "HOPPOP18" character varying COLLATE pg_catalog."default",
    "HOPPOP19" character varying COLLATE pg_catalog."default"
);
END;